---
# ---------------------------------------------------------------------------------------------------------------------
# CircleCI Snippets
#
# Reusable snippets are defined below this section. These are yaml fragments that can injected into the standard
# CircleCI configuration, reducing the complexity of the entire block.
# ---------------------------------------------------------------------------------------------------------------------
docker_image: &docker_snmp_image
  image: 916869144969.dkr.ecr.us-east-1.amazonaws.com/customink/python-ci:bionic
  user: root
  aws_auth:
    aws_access_key_id: ${PRODUCTION_AWS_ACCESS_KEY_ID}
    aws_secret_access_key: ${PRODUCTION_AWS_SECRET_ACCESS_KEY}

deploy_docker_image: &deploy_docker_image
  image: 916869144969.dkr.ecr.us-east-1.amazonaws.com/customink/ktool:v13
  aws_auth:
    aws_access_key_id: ${PRODUCTION_AWS_ACCESS_KEY_ID}
    aws_secret_access_key: ${PRODUCTION_AWS_SECRET_ACCESS_KEY}

# ---------------------------------------------------------------------------------------------------------------------
# CircleCI Commands Configuration
#
# Commands are re-usable steps that can be shared across jobs. For example the installation of gems using bundler or
# waiting on a database connection. By defining them inside the commands section, they can be invoked as any standard
# command on the system, but will already be preconfigured. This allows us to keep the jobs definition small and clean
# ---------------------------------------------------------------------------------------------------------------------
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.16.0

executors:
  # Whenever the Go version is updated here, .promu.yml
  # should also be updated.
  golang:
    docker:
    - image: quay.io/prometheus/golang-builder:1.18-base
    parameters:
      working_dir:
        type: string
        default: ~/project
    working_directory: << parameters.working_dir >>

jobs:
  test:
    executor: golang

    steps:
    - prometheus/setup_environment
    - run: apt-get update
    - run: apt-get -y install build-essential libsnmp-dev
    - run: make
    - run: git diff --exit-code
    - prometheus/store_artifact:
        file: snmp_exporter

  generator:
    executor:
      name: golang
      working_dir: ~/project/generator

    environment:
      MIBDIRS: mibs
    steps:
    - checkout:
        path: ~/project
    - run: apt-get update
    - run: apt-get -y install build-essential diffutils libsnmp-dev p7zip-full
    - run: make mibs
    - run: make generator
    - run: make parse_errors
    - run: make generate
    - run: diff -u ../snmp.yml snmp.yml

  publish_generator_master:
    executor: golang

    steps:
    - prometheus/setup_build_environment:
    - run: make -C generator docker
    - run: make -C generator docker DOCKER_REPO=quay.io/prometheus
    - run: docker images
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - run: docker login -u $QUAY_LOGIN -p $QUAY_PASSWORD quay.io
    - run: make -C generator docker-publish
    - run: make -C generator docker-publish DOCKER_REPO=quay.io/prometheus

  publish_generator_release:
    executor: golang

    steps:
    - prometheus/setup_build_environment:
    - run: make -C generator docker DOCKER_IMAGE_TAG=$CIRCLE_TAG
    - run: make -C generator docker DOCKER_IMAGE_TAG=$CIRCLE_TAG DOCKER_REPO=quay.io/prometheus
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - run: docker login -u $QUAY_LOGIN -p $QUAY_PASSWORD quay.io
    - run: |
        if [[ "$CIRCLE_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
          make -C generator docker-tag-latest DOCKER_IMAGE_TAG="$CIRCLE_TAG"
          make -C generator docker-tag-latest DOCKER_IMAGE_TAG="$CIRCLE_TAG" DOCKER_REPO=quay.io/prometheus
        fi
    - run: make -C generator docker-publish
    - run: make -C generator docker-publish DOCKER_REPO=quay.io/prometheus

  mixin:
    executor: golang

    steps:
    - checkout
    - run: go install github.com/monitoring-mixins/mixtool/cmd/mixtool@latest
    - run: go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest
    - run: make -C snmp-mixin lint build

workflows:
  version: 2
  snmp_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - mixin:
        filters:
          tags:
            only: /.*/
    - prometheus/build:
        name: build
        filters:
          tags:
            only: /.*/
    - generator:
        filters:
          tags:
            only: /.*/
    - prometheus/publish_master:
        context: org-context
        requires:
        - test
        - build
        - generator
        filters:
          branches:
            only: master
    - prometheus/publish_release:
        context: org-context
        requires:
        - test
        - build
        - generator
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
    - publish_generator_master:
        context: org-context
        requires:
        - test
        - build
        - generator
        filters:
          branches:
            only: master
    - publish_generator_release:
        context: org-context
        requires:
        - test
        - build
        - generator
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/