---
# ---------------------------------------------------------------------------------------------------------------------
# CircleCI Snippets
#
# Reusable snippets are defined below this section. These are yaml fragments that can injected into the standard
# CircleCI configuration, reducing the complexity of the entire block.
# ---------------------------------------------------------------------------------------------------------------------
deploy_docker_image: &deploy_docker_image
  image: 916869144969.dkr.ecr.us-east-1.amazonaws.com/customink/ktool:v13
  aws_auth:
    aws_access_key_id: ${PRODUCTION_AWS_ACCESS_KEY_ID}
    aws_secret_access_key: ${PRODUCTION_AWS_SECRET_ACCESS_KEY}

docker_image: &docker_image
  image:  916869144969.dkr.ecr.us-east-1.amazonaws.com/customink/python-ci:bionic 
  aws_auth:
    aws_access_key_id: ${PRODUCTION_AWS_ACCESS_KEY_ID}
    aws_secret_access_key: ${PRODUCTION_AWS_SECRET_ACCESS_KEY}

golang_docker_image: &golang_docker_image
  image: circleci/golang:1.15.8
  # parameters:
  #     working_dir:
  #       type: string
  #       default: ~/project
  # working_directory: << parameters.working_dir >>

# ---------------------------------------------------------------------------------------------------------------------
# CircleCI Commands Configuration
#
# Commands are re-usable steps that can be shared across jobs. For example the installation of gems using bundler or
# waiting on a database connection. By defining them inside the commands section, they can be invoked as any standard
# command on the system, but will already be preconfigured. This allows us to keep the jobs definition small and clean
# ---------------------------------------------------------------------------------------------------------------------
version: 2.1
orbs:
  prometheus: prometheus/prometheus@0.16.0
# orbs:
#   prometheus: prometheus/prometheus@0.16.0
# executors:
#   # Whenever the Go version is updated here, .promu.yml
#   # should also be updated.
#   golang:
#     docker:
#     - image: circleci/golang:1.15.8
#     parameters:
#       working_dir:
#         type: string
#         default: ~/project
#     working_directory: << parameters.working_dir >>
# ---------------------------------------------------------------------------------------------------------------------
# CircleCI Job Configuration
#
# This section defines all the available jobs that can be executed inside a Workflow.
# Think of a Job as a batch of tasks that need to be performed to setup the environment
# and perform a specific task such as running RSpec.
# ---------------------------------------------------------------------------------------------------------------------
jobs:
  ### Build and test the application
  build-and-test:
    working_directory: ~/project/generator
    docker:
      - <<: *golang_docker_image
      - <<: *docker_image
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: |
            apt update -y && \
            apt install -y build-essential libsnmp-dev && \
            go mod download && \
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
      - run:
            name: SNMP-Exporter Image
            command: |
              export AWS_ACCESS_KEY_ID=${PRODUCTION_AWS_ACCESS_KEY_ID}
              export AWS_SECRET_ACCESS_KEY=${PRODUCTION_AWS_SECRET_ACCESS_KEY}
              ktool build-image
  deploy:
    parameters:
      env-name:
        type: string
      access-key:
        type: env_var_name
      secret-key:
        type: env_var_name
    docker:
      - <<: *deploy_docker_image
    working_directory: "/app"
    steps:
      - checkout
      - run:
          name: Deploy to k8s cluster
          command: |
            export AWS_ACCESS_KEY_ID=${<< parameters.access-key >>}
            export AWS_SECRET_ACCESS_KEY=${<< parameters.secret-key >>}
            ktool deploy --stage << parameters.env-name >># Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-deploy:
    jobs:
      - build-and-test:
          context: customink
      - deploy:
          context: customink
          name: staging-deploy
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
                - sf/DCOPS-25205-snmp-scrap
          # Job parameters
          env-name: staging
          access-key: STAGING_AWS_ACCESS_KEY_ID
          secret-key: STAGING_AWS_SECRET_ACCESS_KEY
      - hold:
          type: approval
          requires:
            - staging-deploy
          filters:
            branches:
              only:
                - master
      - deploy:
          context: customink
          name: prod-deploy
          requires:
            - hold
          # Job parameters
          env-name: prod
          access-key: PRODUCTION_AWS_ACCESS_KEY_ID
          secret-key: PRODUCTION_AWS_SECRET_ACCESS_KEY
